spring:
  application:
    name: The Project Backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: {}
    password: pass
    url: jdbc:postgresql://localhost:5432/the_project_database
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

#      exclude: static/**, public/**

